### ISSUE TITLE
ImportError: cannot import name 'Figure' from 'bokeh.plotting'

### ISSUE THREAD

**Issue by YunSeungHoe** [tier4/caret_analyze#383]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [X] I've confirmed the issue is certainly related to this repository. If not, please consider to make a new issue in https://github.com/tier4/caret/issues

### Description

Hi, I followed the tutorial.  https://tier4.github.io/CARET_doc/main/tutorials/visualization/
"Visualizing latency of node chain with message flow" where the following error occurs.

>  $ from caret_analyze.plot import Plot

>> Succeed to find record_cpp_impl. the C++ version will be used.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/caret/ros2_caret_ws/build/caret_analyze/caret_analyze/plot/__init__.py", line 17, in <module>
      from .plot_facade import Plot
  File "/home/caret/ros2_caret_ws/build/caret_analyze/caret_analyze/plot/plot_facade.py", line 21, in <module>
      from .callback_scheduling import CallbackSchedulingPlot, CallbackSchedulingPlotFactory
  File "/home/caret/ros2_caret_ws/build/caret_analyze/caret_analyze/plot/callback_scheduling/__init__.py", line 15, in <module>
      from .callback_scheduling_plot import CallbackSchedulingPlot
  File "/home/caret/ros2_caret_ws/build/caret_analyze/caret_analyze/plot/callback_scheduling/callback_scheduling_plot.py", line 20, in <module>
      from bokeh.plotting import Figure, save, show
ImportError: cannot import name 'Figure' from 'bokeh.plotting' (/home/caret/.local/lib/python3.10/site-packages/bokeh/plotting/__init__.py)**

How do you solve it?

**Comment by ymski** [comment]
@YunSeungHoe 

Sorry for the delay in informing you.
The fix to make bokeh3>0 available has been applied in #391 .
